version: "3.7"
volumes:
  data:
services:
  database: # service database
    image: postgres:14.2-alpine
    container_name: ck_database
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=chicktosa_db
    volumes:
      - data:/var/lib/postgresql/data
      - type: tmpfs # aumenta o espaco de tmpfs > 64mb (corrige problema de deploy em prod)
        target: /dev/shm